services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./logs:/var/log/discord-bot
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*src/main.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
